name: hotel-management

services:
  postgres:
    image: postgres
    container_name: hotel-management-postgres
    environment:
      POSTGRES_DB: hotel-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - hotel-management_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  hotel-management_postgres_data:
